name: deploy-100

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: instakll nodejs
              uses: actions/setup-node@v2.5.1
              with:
                  node-version: "14.X"
            - name: install deps
              run: npm install
            - name: build app
              run: npm run build
            - name: copy dist file with scp
              uses: appleboy/scp-action@master
              with:
                  DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
                  ParsePrivateKey: ${{ secrets.DEPLOY_KEY }}
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{secrets.SSH_KEY }}
                  port: 22
                  source: "dist/"
                  target: ${{secrets.TARGET }}
